name: "Kids Age"
strategy: "static"
no_screen_padding: false
dark_mode: false
refresh_interval: 86400
custom_fields:
  - keyname: "kid_1_name"
    field_type: "text"
    default: "Adam"
    placeholder: "Name of first child"
  - keyname: "kid_1_birthday"
    field_type: "text"
    default: "2025-08-23"
    placeholder: "YYYY-MM-DD"
  - keyname: "kid_2_name"
    field_type: "text"
    default: ""
    placeholder: "Name of second child"
  - keyname: "kid_2_birthday"
    field_type: "text"
    default: ""
    placeholder: "YYYY-MM-DD"
  - keyname: "kid_3_name"
    field_type: "text"
    default: ""
    placeholder: "Name of third child"
  - keyname: "kid_3_birthday"
    field_type: "text"
    default: ""
    placeholder: "YYYY-MM-DD"
  - keyname: "kid_4_name"
    field_type: "text"
    default: ""
    placeholder: "Name of fourth child"
  - keyname: "kid_4_birthday"
    field_type: "text"
    default: ""
    placeholder: "YYYY-MM-DD"
